### PR TITLE
LTE message parsing

### PR DESCRIPTION
**Pull request by martin-heusse**
Adds LTE message support. This code is borrowed from a patch proposed by altaf329@gmail.com in june 2015 and adapted to fit current wireshark code.

### CODE REVIEW

**Comment by E3V3A** [comment]
[This look wrong](https://github.com/martin-heusse/wireshark/blob/7bef40842d38b51f1f6fcf53a0caa659dbe67d83/epan/dissectors/packet-gsmtap.c#L314-L315): 
```c
{ GSMTAP_TYPE_UMTS_RRC,		"LTE RRC" },
{ GSMTAP_TYPE_UMTS_RRC, "LTE MAC" },
```

I think it should be: 
```c
{ GSMTAP_TYPE_LTE_RRC,		"LTE RRC" },
{ GSMTAP_TYPE_LTE_MAC, "LTE MAC" },
```

**Comment by martin-heusse** [comment]
Yes, thank you for pointing it.

**Comment by alagoutte** [comment]
Yes, please push the fix on Gerrit https://code.wireshark.org/review/

**Comment by martin-heusse** [comment]
https://code.wireshark.org/review/#/c/22515/

**Comment by geraldcombs** [comment]
Added to master in g551309a60e via Gerrit. Closing here.

**Pull request closed without merging**
