### PR TITLE
Update sshdump.c

### PR DESCRIPTION
**Pull request by CanadianJeff**
TCPDUMP Support for SSHDUMP

### CODE REVIEW

**Comment by geraldcombs** [comment]
This is a read-only mirror of https://code.wireshark.org/review/ . Can you upload your change there?

**Comment by CanadianJeff** [comment]
great 1 more god damn site I need to register for what horseshit over 1 simple change

**Comment by geraldcombs** [comment]
You can log in using your GitHub credentials. My apologies if that's an undue burden.

**Comment by CanadianJeff** [comment]
please sir make my shitty life easier over this 1 small change so I can get back to being a productive member of society

**Comment by CanadianJeff** [comment]
or help me find the person who is working on sshdump so he can make the change its like tcpdump was made in the stone ages but still amazing it should have been supported from the start

**Comment by CanadianJeff** [comment]
wiresharks comits on github are fucking fucked up as hell
the -P was removed on commit 5b03a42 on Sep 13, 2016
and fucking re added on commit 6fcce37 on Sep 26, 2016
by the same user "crondaemon"
so dont fucking call my pull request garbage that fixes this problem

**Comment by Lekensteyn** [comment]
@CanadianJeff Please stay civil and mind your tone. This issue will be tracked further at https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=12952

**Pull request closed without merging**
